---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure 6/Figure 7.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/272622/articles/396316/master/folder/figures/Figure 6"
    url: "/users/272622/articles/396316/master/file/figures/Figure%206/Figure%207.png"
