---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure 1/Figure 1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/272622/articles/396316/master/file/figures/Figure%201/Figure%201.png"
    folder_url: "/users/272622/articles/396316/master/folder/figures/Figure 1"
