---
version: 2
multicolumn: true
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Thesis_Fig-1_Fig1/Thesis_Fig-1_Fig1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/272622/articles/396316/master/file/figures/Thesis_Fig-1_Fig1/Thesis_Fig-1_Fig1.png"
    folder_url: "/users/272622/articles/396316/master/folder/figures/Thesis_Fig-1_Fig1"
